app/routes.py
import json
import random
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, jsonify, send_file, after_this_request
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from flask_mail import Message
from .models import User, Lesson, Question, UserQuestion, UserLesson
from .utils import *
from . import db, mail
from sqlalchemy import update, insert, delete
from datetime import datetime
#using werkzeug because it offers more flexibility and does not limit algorithm to just bcrypt -> it is also usually faster
#using hashlib would create too much unnecessary work

routes = Blueprint('routes', __name__)
#just telling python that this file is a blueprint for storing all the routes

random.seed()

@routes.route('/', methods = ['GET', 'POST'])
@routes.route('/login', methods = ['GET', 'POST'])
def login():
   if request.method == 'POST':
       username = request.form.get('username')
       password = request.form.get('password')

       user = User.query.filter_by(username = username).first()

       if not user:
           #aka user does not exist
           flash('Incorrect username or username does not exist', category = 'error')
           return render_template('login.html')

       else:
            if check_password_hash(user.password, password):
            #comparing the password stored in the user instance/object to the one entered in the form
               flash('Successful Login', category = 'success')
               login_user(user, remember = True)

               return redirect(url_for('routes.learn'))
               #redirecting the user to the home page if they are sucessful at logging in

            else:
               flash('Incorect password', category = 'error')
               return render_template('login.html')

   return render_template('login.html')


@routes.route('/sign-up', methods = ['GET', 'POST'])
@routes.route('/create-an-account', methods = ['GET', 'POST'])
def signUp():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        confirmPassword = request.form.get('confirmPassword')

        errors = []

        if email == '':
           errors.append('Email cannot be left empty!')

        if username == '':
            errors.append('Username cannot be empty!')

        if password == '':
            errors.append('Password must not be left empty!')

        if not validateEmail(email):
            errors.append('Invalid Email')

        if notUniqueUsername(username):
            errors.append('Username already taken')

        if password != confirmPassword:
            errors.append('Passwords do not match')

        if not validatePassword(password):
            errors.append('Invalid Password')

        print(errors)

        if errors:
            for error in errors:
                flash(error, category = 'error')
            return render_template('signUp.html')

        else:
            newUser = User(email = email, username = username, password = generate_password_hash(password), progress = 0)

            db.session.add(newUser)
            #adding new user entry
            db.session.commit()

            flash('Account created, login to start learning!', category = 'success')
            #provides a confirmation message when account is created successfully

            return redirect(url_for('routes.login'))
            #get user to login with their just-created login credentials

    return render_template('signUp.html')


@routes.route('/logout')
@login_required
#make sure that you must be logged in to log out
def logout():
   logout_user()
   return redirect(url_for('routes.login'))

@routes.route('/forgor-password', methods = ['GET', 'POST'])
def forgorPassword():
   if request.method == 'POST':
       email = request.form.get('email')
       user = User.query.filter_by(email = email).first()
       #checking if the email exists in the database

       if user:
           flash(f'A link to reset your password has been sent to {email}', category = 'success')

           resetToken = generateResetToken(user.email)
           #creating token, which would be saved within the reset link

           msg = Message(subject = 'Luodingo Password Reset', recipients = [email], body = f'Reset password with this link: {url_for(f"routes.resetPassword", token = resetToken, _external = True)}\n\nThis link expires in 1 hour.')
           #_external = True to show the absolute URL, rather than the relative one

           mail.send(msg)
           return redirect(url_for('routes.login'))


       else:
           flash(f'{email} is not in the database, sign up to create an account or try again', category = 'error')
           return render_template('forgorPassword.html')

   return render_template('forgorPassword.html')


@routes.route('/reset-password/<token>', methods = ['GET', 'POST'])
def resetPassword(token):
   email = verifyResetToken(token)

   if not email:
       flash('The reset link is invalid or has expired', category = 'error')
       return redirect(url_for('routes.login')) 

   if request.method == 'POST':
       password = request.form.get('password')
       confirmPassword = request.form.get('confirmPassword')

       errors = []

       if password != confirmPassword:
           errors.append('Passwords do not match')

       if not validatePassword(password):
           errors.append('Invalid Password')

       if errors:
           for error in errors:
               flash(error, category = 'error')
           return render_template('resetPassword.html', token = token)

       else:
           user = User.query.filter_by(email = email).first()

           user.password = generate_password_hash(password)
           db.session.commit()
           flash('Password has been updated', category = 'success')

           return redirect(url_for('routes.login'))

   return render_template('resetPassword.html', token = token)

@routes.route('/reset-username', methods = ['GET', 'POST'])
def resetUsername():
    if request.method == 'POST':
        newUsername = request.form.get('username')

        user = User.query.filter_by(id = current_user.id).first()

        if not notUniqueUsername(newUsername):
            #so username is unique
            user.username = newUsername
            db.session.commit()
            flash('Username has been updated', category = 'success')

        else:
            flash('Username already taken', category = 'error')
            return render_template('resetUsername.html')

    return render_template('resetUsername.html')

@routes.route('/reset-progress', methods = ['GET', 'POST'])
def resetProgress():
    if current_user.email == 'lukz@merciaschool.com':
        if request.method == 'POST':
            userId = request.form.get('userId')

            user = User.query.filter_by(id = userId).first()

            user.progress = 0
            db.session.commit()
            flash('User progress has been reset.', category = 'success')

        return render_template('resetProgress.html')

    else:
        flash('Access restricted... You will be redirected to the learn page.', category='error')
        return redirect(url_for('routes.learn'))

@routes.route('/home', methods = ['GET', 'POST'])
@routes.route('/learn', methods = ['GET', 'POST'])
@login_required
def learn():
    if request.method == 'POST':
        lessonId = int(request.form.get('lesson'))

        return redirect(url_for('routes.lesson', lessonId = lessonId))
    
    userCompletedLessons = UserLesson.query.with_entities(UserLesson.lessonId).filter_by(userId=current_user.id, state='Completed').all()
    #will find all completed lessons of the user (returns a list of tuples)
    userCompletedLessons = [lessonId for (lessonId, ) in userCompletedLessons]

    higherUserRank = User.query.filter(User.progress > current_user.progress).count()
    userRank = higherUserRank + 1

    dailyWord = generateWordOfTheDay()

    existingWords = [entry.word for entry in DailyWord.query.all()]

    if dailyWord not in existingWords:
        db.session.add(dailyWord)
        db.session.commit()

    rightBarData = (userRank, current_user.progress, dailyWord)

    learnLessons = Lesson.query.with_entities(Lesson.id).filter_by(lessonType = 'learn').all()
    learnLessons = [lessonId for (lessonId,) in learnLessons]

    return render_template('learn.html', userCompletedLessons = userCompletedLessons, rightBarData = rightBarData, learnLessons = learnLessons)

@routes.route('/grammar', methods = ['GET', 'POST'])
@login_required
def grammar():
    if request.method == 'POST':
        lessonId = int(request.form.get('lesson'))
        return redirect(url_for('routes.lesson', lessonId = lessonId))
    
    userCompletedLessons = UserLesson.query.with_entities(UserLesson.lessonId).filter_by(userId=current_user.id, state='Completed').all()
    userCompletedLessons = [lessonId for (lessonId, ) in userCompletedLessons]

    higherUserRank = User.query.filter(User.progress > current_user.progress).count()
    userRank = higherUserRank + 1

    dailyWord = generateWordOfTheDay()

    existingWords = [entry.word for entry in DailyWord.query.all()]

    if dailyWord not in existingWords:
        db.session.add(dailyWord)
        db.session.commit()

    rightBarData = (userRank, current_user.progress, dailyWord)

    grammarLessons = Lesson.query.with_entities(Lesson.id).filter_by(lessonType = 'grammar').all()
    grammarLessons = [lessonId for (lessonId,) in grammarLessons]

    return render_template('grammar.html', userCompletedLessons = userCompletedLessons, rightBarData = rightBarData, grammarLessons = grammarLessons)

@routes.route('/retrieval', methods = ['GET', 'POST'])
@login_required
def retrieval():
    if request.method == 'POST':

app/templates/addLesson.html
{% extends 'base.html' %}
<!-- extending from base because the forms are quite similar to login forms -->
{% block title %}Add Lesson{% endblock %}

{% block content %}
<form method = 'POST' action = '{{ url_for("routes.addLesson") }}'>

    <h1>Add a Lesson</h1>
    <div class = 'form-group'>
        <input type = 'json' id = 'lesson' name = 'lesson' placeholder = 'Lesson'>
        <br>
        <input type = 'text' id = 'notes' name = 'lessonType' placeholder = 'Lesson Type'>
        <br>
        <input type = 'text' id = 'notes' name = 'notes' placeholder = 'Notes'>
        <br>
        <button type = 'submit'><b>Create Lesson</b></button>
    </div>

</form>

{% if lessons %}
    <h2>All Lessons</h2>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Deck – elements inside deck are questionIds</th>
            <th>Lesson Type</th>
            <th>Notes</th>
        </tr>

        {% for lesson in lessons %}
        <tr>
            <td>{{ lesson.id }}</td>
            <td>{{ lesson.deck }}</td>
            <td>{{ lesson.lessonType}}</td>
            <td>{{ lesson.notes }}</td>
            <td>
                <form method="POST" action="{{ url_for('routes.deleteLesson', lessonId=lesson.id) }}">
                    <button type="submit">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No lessons found.</p>
{% endif %}

{% if questions %}
    <h2>All Questions</h2>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Deck</th>
            <th>Answer</th>
            <th>Type</th>
            <th>Options</th>
        </tr>

        {% for question in questions %}
        <tr>
            <td>{{ question.id }}</td>
            <td>{{ question.question }}</td>
            <td>{{ question.answer }}</td>
            <td>{{ question.questionType }}</td>
            <td>{{ question.options }}</td>
            <td>
                <form method="POST" action="{{ url_for('routes.deleteQuestion', questionId=question.id) }}">
                    <button type="submit">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No questions found.</p>
{% endif %}


{% endblock %}

app/templates/grammar.html
{% extends 'appBase.html' %}
{% block title %}Learn{% endblock %}

{% block content %}
    <form method = 'POST' action = "{{ url_for('routes.grammar') }}">
        <div class='card grammar-card'>
            <div class='card-body'>
                <h1 class='custom-card-header'>A1: Foundational</h1>
            </div>
        </div>

        <div class='container lesson-container'>
            {% if grammarLessons[0] not in userCompletedLessons %}
                <button type = 'submit' id='button1' name = 'lesson' value = '{{ grammarLessons[0] }}' class='grammar-button'>
                    <div class='book-icon'></div>
                </button>
            {% else %}
                <button type = 'submit' id='button1' name = 'lesson' value = '{{ grammarLessons[0] }}' class='lesson-completed-button'>
                    <div class='tick-icon'></div>
                </button>
            {% endif %}
            <p class='lesson-text'>Personal Pronouns</p>
        </div>

        <div class='row'>
            <div class='col-md-3'>
                <div class='container lesson-container'>
                    {% if grammarLessons[1] not in userCompletedLessons %}
                        <button type = 'submit' id='button2' name = 'lesson' value = '{{ grammarLessons[1] }}' class='grammar-button'>
                            <div class='book-icon'></div>
                        </button>
                    {% else %}
                        <button type = 'submit' id='button2' name = 'lesson' value = '{{ grammarLessons[1] }}' class='lesson-completed-button'>
                            <div class='tick-icon'></div>
                        </button>
                    {% endif %}
                    <p class='lesson-text'>'sein'</p>
                </div>
            </div>

            <div class='col-md-6'>
            </div>

            <div class='col-md-3'>
                <div class='container lesson-container'>
                    {% if grammarLessons[2] not in userCompletedLessons %}
                        <button type = 'submit' id='button3' name = 'lesson' value = '{ {grammarLessons[2] }}' class='grammar-button'>
                            <div class='book-icon'></div>
                        </button>
                    {% else %}
                        <button type = 'submit' id='button3' name = 'lesson' value = '{{ grammarLessons[2] }}' class='lesson-completed-button'>
                            <div class='tick-icon'></div>
                        </button>
                    {% endif %}
                    <p class='lesson-text'>'haben'</p>
                </div>
            </div>

            <div class='container lesson-container'>
                {% if grammarLessons[3] not in userCompletedLessons %}
                    <button type = 'submit' id='button4' name = 'lesson' value = '{{ grammarLessons[3] }}' class='grammar-button'>
                        <div class='book-icon'></div>
                    </button>
                {% else %}
                    <button type = 'submit' id='button4' name = 'lesson' value = '{{ grammarLessons[3] }}' class='lesson-completed-button'>
                        <div class='tick-icon'></div>
                    </button>
                {% endif %}
                <p class='lesson-text'>Articles</p>
            </div>
        </div>
    </form>

{% endblock %}

app/templates/questionResult.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
   <!-- linking to boostrap here -->
   <link rel = 'stylesheet' href='{{ url_for("static", filename="style.css") }}'>
   <link rel = 'shortcut icon' href = '{{ url_for("static", filename = "favicon-16x16.png") }}'>
  <title>Question</title>
</head>

{% with messages = get_flashed_messages(with_categories=true) %}
   {% if messages %}
       {% for category, message in messages %}
           {% set alertClass = 'alert-danger' if category == 'error' else 'alert-success' %}
           <!-- rather than needing an if-else block , this just uses one line to set the value of alertClass-->
           <div class='alert {{ alertClass }} alert-dismissable fade show' role='alert'>
               {{ message }}
               <button type='button' class='close' data-dismiss='alert'>
                   <span aria-hidden='true'>&times;</span>
               </button>                 
           </div>
       {% endfor %}
   {% endif %}
{% endwith %}

<body>
    <div class = 'question-parent-container'>
        <div class = 'question-main-content'>
            <div class = 'question-top-container'>
                <div class = 'row question-top-bar'>
                    <div class = 'question-exit-button'>
                        {% if lesson.lessonType == 'retrieval' %}
                            <a href = "{{ url_for('routes.retrieval') }}" class = 'btn' onclick='return confirmExit()'>&times;</a>
                        {% elif lesson.lessonType == 'grammar' %}
                        <!-- hard coded in for now, weirdly, I get red highlighting when I use the '<' symbol-->
                            <a href = "{{ url_for('routes.grammar') }}" class = 'btn' onclick='return confirmExit()'>&times;</a>
                        {% else %}
                            <a href = "{{ url_for('routes.learn') }}" class = 'btn' onclick='return confirmExit()'>&times;</a>
                        {% endif %}
                    </div>
        
                    <div class = 'progress-wrapper'>
                        <div class = 'progress'>
                            <div class = 'progress-bar progress-bar-striped' role = 'progressbar' style = 'width: {{ progress }}%;' aria-valuenow = '0' aria-valuemin = '0' aria-valuemax = '100'></div>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class = 'question-content-container'>
                <div class = 'question-content-elements-container'>
                    {% if question.questionType == 'multiple-choice' %}
                        <h1> Select the correct meaning </h1>
                        <p> Wie sagt man "<b> {{ question.question }} </b>" auf Deutsch? </p>
        
                        <audio id = 'audio' autoplay controls>
                            <source src = '{{ audioPath }}' type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                        <br>
        
                        <button type = 'button' class = 'option-button option1-button' onclick = 'selectOption(this, "{{ option1 }}")'>{{ option1 }}</button>
                        <br>
                        <button type = 'button' class = 'option-button option2-button' onclick = 'selectOption(this, "{{ option2 }}")'>{{ option2 }}</button>
                        <br>
                        <button type = 'button' class = 'option-button option3-button' onclick = 'selectOption(this, "{{ option3 }}")'>{{ option3 }}</button>
                        <br>
                        <input type = 'hidden' name = 'answer' id = 'selectedOption' value = ''>
        
                    {% elif question.questionType == 'fill-in-the-blank' %}
                        <h1> Fill in the blank </h1>
                        <p> <b> {{ questionLeft }} </b> <img src = '/static/blank.png' alt = 'blank'> <b> {{ questionRight }}</b></p>
        
                        <audio autoplay controls>
                            <source src = '{{ audioPath }}' type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                        <br>
        
                        <button type = 'button' class = 'option-button option1-button' onclick = 'selectOption(this, "{{ option1 }}")'>{{ option1 }}</button>
                        <br>
                        <button type = 'button' class = 'option-button option2-button' onclick = 'selectOption(this, "{{ option2 }}")'>{{ option2 }}</button>
                        <br>
                        <button type = 'button' class = 'option-button option3-button' onclick = 'selectOption(this, "{{ option3 }}")'>{{ option3 }}</button>
                        <br>
                        <input type = 'hidden' name = 'answer' id = 'selectedOption' value = ''>
        
                    {% elif question.questionType == 'keyboard-input' %}
                    <h1> Write this in German </h1>
                    <p>"{{ question.question }}"</p>
        
                    <audio autoplay controls>
                        <source src = '{{ audioPath }}' type="audio/mpeg">
                        Your browser does not support the audio element.
                    </audio>
        
                    <br>
        
                    <div class = 'keyboard-input-answer-container'>
                        <textarea id = 'text-box' type = 'text' name = 'answer' placeholder = 'Type here in German' class = 'form-control mb-1 keyboard-input-text-box'></textarea>
                        <!-- id is text-box so that the javaScript function could work -->
                    </div>
        
                    <br>
        
                    <!-- buttons of accents -->
                    <div class = 'accent-container'>
                                <button type = 'button' name = 'accent' value = 'Ä' onclick = 'addString("Ä")' class = 'ä-capital-button'></button>
                                <button type = 'button' name = 'accent' value = 'Ö' onclick = 'addString("Ö")' class = 'ö-capital-button'></button>
                                <button type = 'button' name = 'accent' value = 'Ü' onclick = 'addString("Ü")' class = 'ü-capital-button'></button>
                                <button type = 'button' name = 'accent' value = 'ä' onclick = 'addString("ä")' class = 'ä-button'></button>
                                <button type = 'button' name = 'accent' value = 'ö' onclick = 'addString("ö")' class = 'ö-button'></button>
                                <button type = 'button' name = 'accent' value = 'ü' onclick = 'addString("ü")' class = 'ü-button'></button>
                                <button type = 'button' name = 'accent' value = 'ß' onclick = 'addString("ß")' class = 'ß-button'></button>
                    </div>
        
                    {% elif question.questionType == 'mouse-navigation' %}
                        <div class = 'mouse-nav-container'>
                            <h1> Write this in English </h1>
                            <p>"{{ question.question }}"</p>
        
                            <audio autoplay controls>
                                <source src = '{{ audioPath }}' type="audio/mpeg">
                                Your browser does not support the audio element.
                            </audio>
        
                            <br>
        
                            <div class = 'mouse-nav-button-container'>
                                <div id = 'button-container' class = 'mouse-nav-answer-button-container'>
                                    <div class = 'sentence-line top'></div>
                                    <div class = 'sentence-line bottom'></div>
                                    <!-- tried to make dynamic lines, but didn't work well. This will work for now.-->
                                </div>
                                <!-- in theory will store all the created buttons -->
        
                                <br>
        
                                <div class = 'mouse-nav-default-button-container'>
                                    {% for word in answerList %}
                                        <button type = 'button' name = 'word' value = '{{ word }}' class = 'mouse-nav-button'>{{ word }}</button>
                                    {% endfor %}
                                </div>
                            </div>
        
                            <input id = 'text-box' name = 'answer' style = 'display: none;'>
                            <!-- inviisble text box to track the user's inputs -->
                        </div>
                    {% else %}
                            <!-- mic-input -->
                            <h1 id = 'speech-title' data-enable-recognition = 'true' class = 'speech-header'>Speak this sentence in German</h1>
                            <!-- adding custom attribute for this heading, so that microphonoe permission prompt only pops up for mic-input questions -->
                            <!-- id attribute is also needed for the purpose mentioned on the above comment -->
            
                            <audio autoplay controls class = 'speech-audio-container'>
                                <source src = '{{ audioPath }}' type="audio/mpeg">
                                Your browser does not support the audio element.
                            </audio>
        
                            <div class = 'speech-prompt-container'>
                                <p>"{{ question.question }}"</p>
                            </div>
                            <!-- modification from the design section, where the question will be in English, and user has to translate to German -->
        
                            <h3>Transcription</h3>
                            <div class = 'transcription-container'>
                                <p id = 'transcription'></p>
                            </div>
        
                            <br>
        
                            <button id = 'toggle-speech' class = 'click-to-speech'></button>
        
                            <br>
        
                            <button id = 'clear-transcription' class = 'reset-speech'></button>
            
                            <input id = 'text-box' type = 'hidden' name = 'answer'>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <script src = "{{ url_for('static', filename = 'script.js') }}"></script>
    <!-- moved js code to its own file in script.js -->

</body>

<footer class = 'question-footer'>
    <form method = 'POST' action = "{{url_for('routes.result', questionId = question.id, lessonId = lesson.id, result = result)}}">
        {% if result == 'correct' %}
            <div class = 'correct-answer-footer'>
                <div class = 'correct-tick'></div>
                <h1 class = 'correct-message'>{{ message }}</h1>
                <button type = 'submit' class = 'continue-button-green'></button>
            </div>

        {% else %}
            <div class = 'incorrect-answer-footer'>
                <div class = 'incorrect-cross'></div>
                <div class = 'incorrect-message'>
                    <h4> {{ message }} </h4>
                    <p> {{ question.answer }}</p>
                </div>
                <button type = 'submit' class = 'continue-button-red'></button>
            </div>

        {% endif %}
    </form>
</footer>
  <!-- needed to determine whether the answer is correct or incorrect -->

</html>

app/templates/resetProgress.html
{% extends 'base.html' %}
{% block title %}Reset Progress{% endblock %}


{% block content %}
<form method = 'POST' action = "{{ url_for('routes.resetProgress') }}">
   
   <h1>Reset Progress</h1>
   <div class = 'form-group'>
       <input type = 'number' id = 'userId' name = 'userId' placeholder = 'userId'>
       <br>
       <button type = 'submit'><b>Reset Progress</b></button>
   </div>


</form>
{% endblock %}

app/templates/resetUsername.html
{% extends 'base.html' %}
{% block title %}Reset Username{% endblock %}


{% block content %}
<form method = 'POST' action = "{{ url_for('routes.resetUsername') }}">

    <div class = 'reset-username-parent-container'>
        <div class = 'reset-username-content-container'>

            <div class = 'login-exit-button'>
                <a href = "{{ url_for('routes.profile') }}" class = 'btn'>&times;</a>
                <!-- allow user to return to profile page -->
            </div>

            <h1 class = 'reset-username-title'>Reset Username</h1>

            <div class = 'reset-username-body-container'>
                <input type = 'text' id = 'username' name = 'username' placeholder = 'Username' class = 'reset-username-username'>
                <button type = 'submit' class = 'reset-username-button'><b>RESET USERNAME</b></button>
            </div>

        </div>
    </div>


</form>
{% endblock %}

app/templates/retrieval.html
{% extends 'appBase.html' %}

{% block title %}Retrieval{% endblock %}

{% block content %}
<form method = 'POST' action = "{{ url_for('routes.retrieval') }}">
    <div class='card retrieval-card'>
        <div class='card-body'>
            <h1 class='custom-card-header'>Retrieval</h1>
        </div>
    </div>

    <div class='container lesson-container'>
        <button type = 'submit' class='retrieval-button'>
            <div class='brain-icon'></div>
        </button>
        <p class='lesson-text'>Retrieval Deck</p>
    </div>
</form>
{% endblock %}

app/templates/signUp.html
{% extends 'base.html' %}
{% block title %}Create an Account{% endblock %}


{% block content %}
<form method = 'POST' action = "{{ url_for('routes.signUp') }}">
    <div class = 'sign-up-parent-container'>
        <div class = 'sign-up-content-container'>

            <div class = 'login-exit-button'>
                <a href = "{{ url_for('routes.login') }}" class = 'btn'>&times;</a>
                <!-- allow user to return to login page -->
            </div>

            <h1 class = 'sign-up-title'>Create an Account</h1>

            <div class = 'sign-up-body-container'>
                <input type = 'text' id = 'email' name = 'email' placeholder = 'Email' class = 'sign-up-email'>
                <input type = 'text' id = 'username' name = 'username' placeholder = 'Username' class = 'sign-up-username'>
                <input type = 'password' id = 'password' name = 'password' placeholder = 'Password' class = 'sign-up-password'>
                <p class = 'password-requirements'>Passwords must: be 8 characters long and contain 1 capital letter, 1 number and 1 special character.</p>
                <input type = 'password' id = 'confirmPassword' name = 'confirmPassword' placeholder = 'Confirm Password' class = 'sign-up-confirm-password'>
                <button type = 'submit' class = 'sign-up-button'><b>CREATE ACCOUNT</b></button>
            </div>

            <div class = 'sign-up-footer'>
                <p class = 'sign-up-link-text'>Got an account? <a href = 'login'>Login</a></p>
            </div>
        </div>
    </div>

</form>
{% endblock %}